# Generated by Django 5.1.1 on 2024-09-28 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_passwords', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='password',
            old_name='encripted_password',
            new_name='encrypted_password',
        ),
    ]
